Examcsharp/Examcsharp/Models/Orders.cs
using Examcsharp.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Examcsharp.Models
{
    public class Orders
    {
        public Orders()
        {
            EntityList = new List<Order>();
            ToyList =new List<Toy>();
        }

        public List<Order> EntityList { get; private set; }


        public List<Toy> ToyList { get; private set;}


        public decimal TotCost = 0;
    }
}

Examcsharp/Examcsharp/Controllers/OrdersController.cs
using MongoDB.Bson;
using Examcsharp.Classes;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Examcsharp.Models;
using ExamMongoDb = Examcsharp.Classes.MongoDb;

namespace Examcsharp.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Orders
        public ActionResult Index()
        {
            if (Session["IsAdmin"] != null)
            {
                ExamMongoDb db = new ExamMongoDb();
                var orders = db.GetAllOrder();
                var toys = db.GetAllToy();
                Orders model = new Orders();
                model.EntityList.AddRange(orders);
                model.ToyList.AddRange(toys.ToList());
                    
                
                return View(model);
            }
            else
            {
                return RedirectToAction($"../Users/Login");
            }

        }

        public ActionResult Details(string id)
        {
            if (Session["IsAdmin"] != null)
            {
                ExamMongoDb db = new ExamMongoDb();

                var orders = db.GetOrder(id);
                Order model = new Order();
                model.ID = orders.ID;
                model.RequestDate = orders.RequestDate;
                model.Kid = orders.Kid;
                model.Toys= orders.Toys;
                model.Status = orders.Status;
                
                return View(model);
               

            }
            else
            {
                return RedirectToAction($"../Users/Login");
            }


        }

        public ActionResult Edit(string id)
        {
            if (Session["IsAdmin"] != null)
            {
                ExamMongoDb db = new ExamMongoDb();
                ViewBag.TypeStatus = new TypeStatus();
                var order = db.GetOrder(id);
                Order model = new Order();
                model.ID = order.ID;
                model.Kid = order.Kid;
                model.Status = order.Status;
                model.RequestDate = order.RequestDate;
                model.Toys = order.Toys;
                return View(model);
            }
            else
            {
                return RedirectToAction($"../Users/Login");
            }
        }

        public ActionResult Save(string id, TypeStatus typeStatus)
        {

            if (Session["IsAdmin"] != null || typeStatus.Equals(TypeStatus.Done))
            {
                ExamMongoDb db = new ExamMongoDb();
                bool result;
                var order = db.GetOrder(id);
                var toys = db.GetAllToy().ToList();
                bool allToysIsPresent = ControlToy(order, toys);
                
                


                if ( allToysIsPresent == true || typeStatus.ToString() == "Progress")
                {
                    switch (order.Status.ToString())
                    {
                        case "Progress":
                            if (typeStatus.ToString() != "Progress")
                            {
                                RemoveToy(db, order, toys);
                                result = db.UpdateOrder(new Order
                                {
                                    ID = id,
                                    Status = typeStatus
                                });
                            }
                            break;
                        case "Ready-To-Send":
                            if (typeStatus.ToString() == "Progress")
                            {
                                AddToy(db, order, toys);
                                result = db.UpdateOrder(new Order
                                {
                                    ID = id,
                                    Status = typeStatus
                                });
                            }
                            else if (typeStatus == TypeStatus.Done)
                            {
                                if (typeStatus.ToString() != "Progress")
                                {
                                    RemoveToy(db, order, toys);
                                    result = db.UpdateOrder(new Order
                                    {
                                        ID = id,
                                        Status = typeStatus
                                    });
                                }
                            }
                            break;
                    }
                    return RedirectToAction("Index");
                }
                
                
              return  RedirectToAction($"../Toys/MissingToy");
                
                
                //return RedirectToAction("Index",new {result=result});
            }
            
            
            return RedirectToAction($"../Users/Login");
            
            
        }
   

        private bool ControlToy(Order order, List<Toy> toys)
        {
            foreach (var toyOrder in order.Toys)
            {
                foreach (var toy in toys)
                {
                    if (toy.Name == toyOrder.Name)
                    {
                        if (toy.Amount == 0)
                        {
                            return false;
                        }
                    }
                }
            }
            return true;
        }
     
        private void RemoveToy(ExamMongoDb db, Order order, List<Toy> toys)
        {
            bool result;
            foreach (var toyOrder in order.Toys)
            {
                foreach (var toy in toys)
                {
                    if (toy.Name.Equals(toyOrder.Name))
                    {
                        result = db.UpdateToy(new Toy
                        {
                            ID = toy.ID,
                            Name = toy.Name,
                            Amount = toy.Amount - 1
                        });
                    }
                }
            }
        }
     
        private void AddToy(ExamMongoDb db, Order order, List<Toy> toys)
        {
            bool result;
            foreach (var toyOrder in order.Toys)
            {
                foreach (var toy in toys)
                {
                    if (toy.Name.Equals(toyOrder.Name))
                    {
                        result = db.UpdateToy(new Toy
                        {
                            ID = toy.ID,
                    
                            Name = toy.Name,
                            Amount = toy.Amount + 1
                        });
                    }
                }
            }
        }
     
        
    }
}

Examcsharp/Examcsharp/Views/Orders/Details.cshtml
@using Examcsharp.Classes
@model Order
@{
    ViewBag.Title = "Details";
}

<h2 style="text-align:center";>Orders Details</h2>

<div>
    <h4 style="text-align: center;">Christmas Orders</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Kid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RequestDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    <table class="table">
        <thead>
        <tr>
            <th>Toys</th>
            <th></th>
          
        </tr>
        </thead>
        <tbody>
        @foreach (var toy in Model.Toys)
        {
            <td>@toy.Name</td>
        }
            
    
        </tbody>
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID, typeStatus=Model.Status}, new { @class = "btn btn-default glyphicon glyphicon-pencil" })
</p>

@Html.ActionLink(" Back", "Index", null, new { @class = "btn btn-primary" })

Examcsharp/Examcsharp/Views/Orders/Edit.cshtml
@using Examcsharp.Classes
@model Order

@{
  ViewBag.Title = "Edit";
}

<h2 style="text-align:center;">Edit Orders</h2>

@using (Html.BeginForm("Save", "Orders"))
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4 style="text-align: center;">Edit Status Order</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
      <dt>
        @Html.DisplayNameFor(model => model.ID)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.ID)
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.Kid)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Kid)
      </dd>
      
      <dt>
        @Html.DisplayNameFor(model => model.RequestDate)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.RequestDate)
      </dd>
      
    </dl>
    <table class="table">
      <thead>
      <tr>
        <th>Toys</th>
        <th></th>
          
      </tr>
      </thead>
      <tbody>
      @foreach (var toy in Model.Toys)
      {
        <td>@toy.Name</td>
      }
            
    
      </tbody>
    </table>
    <div class="form-group">
      @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        <select id="TypeStatus" name="TypeStatus" class="btn btn-default btn-lg dropdown-toggle">
          @foreach (var status in Enum.GetValues(typeof(TypeStatus)))
          {
            if (Model.Status.Equals(@status))
            {
              <option value="@status" selected="selected">@status</option>
            }
            else
            {
              <option value="@status">@status</option>
            }
          }
        </select>
        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
      </div>
    </div>

    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Save" class="btn btn-success" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink(" Back", "Index", null, new { @class = "btn btn-primary" })
</div>

Examcsharp/Examcsharp/Views/Orders/Index.cshtml
@using Examcsharp.Classes
@using Examcsharp.Models

@{
    ViewBag.Title = "Orders";
}
@model Orders


<div class="row">
    <div class="col-xs-12">
        <h2 style="text-align:center;">Orders</h2>
    </div>
</div>
<table class="table">
    <thead>
    <tr>
        <th>Kid</th>
        <th>Request-Date</th>
        <th>Status</th>
        <th></th>
        @if (Session["IsAdmin"].Equals(true))
        {
            <th>Num.Toys</th>
            <th>Cost.Tot</th>
        
        }
        
    </tr>
    </thead>
    <tbody>
    @foreach (var orders in Model.EntityList)
    {
        Model.TotCost = 0;
        var colorAlert = "alert-danger";
        if (orders.Status == TypeStatus.Ready_To_Send)
        {
            colorAlert = "alert-warning";
        }
        else if (orders.Status == TypeStatus.Done)
        {
            colorAlert = "alert-success";
        }
        
            
        
        <tr class=@colorAlert>
            
            <td>
                @Html.Label(orders.Kid)
            </td>
            <td>
                @Html.Label(orders.RequestDate.ToString())
            </td>
            <td>
                @Html.Label(orders.Status.ToString())
                
            </td>
           
            <td>
                @if (Session["IsAdmin"].Equals(false))
                {
                    
                    <th>@Html.ActionLink("Details", "Details", new {id = orders.ID}, new {@class = "btn btn-info"})</th>
                    <th>@Html.ActionLink("Edit", "Edit", new {id = orders.ID, date = orders.Status}, new {@class = "btn btn-default glyphicon glyphicon-pencil"})</th>
                }
                else
                {
                    <th>@orders.ToysNumber()</th>    
                    foreach (var toy in orders.Toys)
                    {
                        if (Session["IsAdmin"].Equals(true))
                        {
                            foreach (var toyForCost in Model.ToyList)
                            {
                                if (toy.Name == toyForCost.Name)
                                {
                                    Model.TotCost += toyForCost.Cost;
                                     
                                }
                            }
                        }
                    }
                        
                    
                    <th>@string.Concat(Model.TotCost.ToString("F"),"€")</th>
        
                }
                
            </td>
        </tr>
    }
    
    </tbody>
</table>